# Generated by Django 5.1.1 on 2024-11-03 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("home_latitude", models.FloatField(blank=True, null=True)),
                ("home_longitude", models.FloatField(blank=True, null=True)),
                ("work_latitude", models.FloatField(blank=True, null=True)),
                ("work_longitude", models.FloatField(blank=True, null=True)),
                ("fav_source_latitude", models.FloatField(blank=True, null=True)),
                ("fav_source_longitude", models.FloatField(blank=True, null=True)),
                ("fav_dest_latitude", models.FloatField(blank=True, null=True)),
                ("fav_dest_longitude", models.FloatField(blank=True, null=True)),
                ("score", models.IntegerField(default=0)),
                (
                    "fav_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.station",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField(default=0)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.station"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
