# Generated by Django 5.1.1 on 2024-11-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_profile_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
