# Generated by Django 5.1.1 on 2024-11-06 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_review_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to="app.station",
            ),
        ),
    ]
